import React, { createContext, useContext, useState } from "react";

type Language = "vi" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

// Simple translation function (you can expand this)
const translations = {
  vi: {
    // Header
    "header.about": "Giới thiệu",
    "header.search": "Tìm kiếm phim...",
    "header.login": "Đăng nhập",
    "header.profile": "Hồ sơ",
    "header.dashboard": "Bảng điều khiển",
    "header.logout": "Đăng xuất",
    // Home
    "home.hero.title": "CINEHUB",
    "home.hero.subtitle": "Trải nghiệm điện ảnh đỉnh cao",
    "home.nowPlaying": "PHIM ĐANG CHIẾU",
    "home.upcoming": "PHIM SẮP CHIẾU",
    "home.promotions": "KHUYẾN MÃI",
    "home.contact": "LIÊN HỆ",
    "home.learnMore": "Tìm hiểu thêm",
    "home.bookTicket": "Đặt vé",
    "home.bookNow": "Đặt ngay",
    "home.seeMore": "Xem thêm",
    "home.noMoviesPlaying": "Không có phim nào đang chiếu",
    "home.noMoviesUpcoming": "Không có phim nào sắp chiếu",
    // Quick Booking Bar
    "home.booking.title": "ĐẶT VÉ NHANH",
    "home.booking.movie": "Chọn phim",
    "home.booking.theater": "Chọn rạp",
    "home.booking.date": "Chọn ngày",
    "home.booking.showtime": "Chọn suất",
    "home.booking.bookNow": "Đặt ngay",
    // Footer
    "footer.theaterSystem": "Hệ thống rạp",
    "footer.contact": "Liên hệ",
    "footer.policy": "Chính sách",
    "footer.privacyPolicy": "Chính sách bảo mật",
    "footer.description":
      "CineHub - Hệ thống rạp chiếu phim hiện đại, mang đến trải nghiệm điện ảnh đỉnh cao với công nghệ tiên tiến nhất.",
    "footer.rights": "Tất cả quyền được bảo lưu.",
    // Search
    "search.resultsFor": "Kết quả tìm kiếm cho",
    "search.found": "Tìm thấy",
    "search.movies": "phim",
    "search.and": "và",
    "search.theatersCount": "rạp",
    "search.moviesSection": "PHIM",
    "search.theaters": "RẠP CHIẾU PHIM",
    "search.book": "Đặt vé",
    "search.enterKeyword": "Vui lòng nhập từ khóa tìm kiếm",
    "search.noResults": "Không tìm thấy kết quả nào",
    // Contact
    "contact.university": "UIT - Trường Đại học Công nghệ Thông tin",
    "contact.address": "Địa chỉ",
    "contact.description":
      "Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn. Hãy liên hệ với chúng tôi qua các kênh bên dưới.",
    "contact.title": "Gửi tin nhắn cho chúng tôi",
    "contact.name": "Họ và tên",
    "contact.namePlaceholder": "Nhập họ và tên của bạn",
    "contact.nameRequired": "Vui lòng nhập họ tên",
    "contact.nameMinLength": "Họ tên phải có ít nhất 2 ký tự",
    "contact.email": "Email",
    "contact.emailRequired": "Vui lòng nhập email",
    "contact.emailInvalid": "Email không hợp lệ",
    "contact.message": "Nội dung",
    "contact.messagePlaceholder": "Nhập nội dung tin nhắn...",
    "contact.messageRequired": "Vui lòng nhập nội dung",
    "contact.messageMinLength": "Nội dung phải có ít nhất 10 ký tự",
    "contact.messageMaxLength": "Nội dung không được vượt quá 1000 ký tự",
    "contact.send": "Gửi tin nhắn",
    "contact.sending": "Đang gửi...",
    "contact.success": "Thành công!",
    "contact.successMessage":
      "Tin nhắn của bạn đã được gửi thành công. Chúng tôi sẽ phản hồi sớm nhất có thể.",
    "contact.error": "Lỗi!",
    "contact.errorMessage":
      "Có lỗi xảy ra khi gửi tin nhắn. Vui lòng thử lại sau.",
    // Common
    "common.loading": "Đang tải...",
    "common.confirm": "Xác nhận",
    // Profile
    "profile.loading": "Đang tải...",
    "profile.cannotLoad": "Không thể tải thông tin hồ sơ",
    "profile.info": "Thông tin",
    "profile.bookings": "Lịch sử đặt vé",
    "profile.fnb": "Bắp nước",
    "profile.favorites": "Phim yêu thích",
    "profile.loyalty": "Lịch sử tích lũy",
    "profile.notUpdated": "Chưa cập nhật",
    "profile.edit": "Chỉnh sửa",
    "profile.ticketsBooked": "Vé đã đặt",
    "profile.favoriteMovies": "Phim yêu thích",
    "profile.loyaltyPoints": "Điểm tích lũy",
    "profile.memberRank": "Hạng thành viên : ",
    "profile.rankProgress": "Tiến độ hạng",
    "profile.fullName": "Họ và tên",
    "profile.email": "Email",
    "profile.phone": "Số điện thoại",
    "profile.gender": "Giới tính",
    "profile.male": "Nam",
    "profile.female": "Nữ",
    "profile.other": "Khác",
    "profile.address": "Địa chỉ",
    "profile.dateOfBirth": "Ngày sinh",
    "profile.nationalId": "CCCD",
    "profile.status": "Trạng thái",
    "profile.createdDate": "Ngày tạo",
    "profile.active": "Hoạt động",
    "profile.blocked": "Bị khóa",
    "profile.noBookingHistory": "Chưa có lịch sử đặt vé",
    "profile.bookingHistoryDesc": "Lịch sử đặt vé của bạn sẽ hiển thị ở đây",
    "profile.bookingCode": "Mã đặt vé",
    "profile.theater": "Rạp",
    "profile.room": "Phòng",
    "profile.showtime": "Suất chiếu",
    "profile.seats": "Ghế",
    "profile.seeMore": "Xem thêm",
    "profile.noFavoriteMovies": "Chưa có phim yêu thích",
    "profile.favoriteMoviesDesc": "Thêm phim yêu thích để xem lại sau",
    "profile.noFnbHistory": "Chưa có lịch sử đặt bắp nước",
    "profile.fnbHistoryDesc": "Lịch sử đặt bắp nước của bạn sẽ hiển thị ở đây",
    "profile.orderNow": "Đặt ngay",
    "profile.fnbOrder": "Đơn bắp nước",
    "profile.orderCode": "Mã đơn",
    "profile.confirmed": "Đã xác nhận",
    "profile.pending": "Đang chờ",
    "profile.cancelled": "Đã hủy",
    "profile.orderedItems": "Sản phẩm đã đặt",
    "profile.orderTime": "Thời gian đặt",
    "profile.total": "Tổng cộng",
    "profile.membershipRank": "Hạng thành viên",
    "profile.currentPoints": "Điểm hiện tại",
    "profile.pointsRemaining": "Còn",
    "profile.pointsToNext": "điểm để lên hạng tiếp theo",
    "profile.loyaltyHistory": "Lịch sử điểm thưởng",
    "profile.noLoyaltyHistory": "Chưa có lịch sử điểm thưởng",
    "profile.loyaltyHistoryDesc": "Đặt vé xem phim để tích điểm thưởng",
    "profile.bookNow": "Đặt ngay",
    "profile.exploreMovies": "Khám phá phim",
    "profile.earned": "Nhận được",
    "profile.redeemed": "Đã đổi",
    "profile.bonus": "Thưởng",
    "profile.expired": "Hết hạn",
    "profile.points": "điểm",
    "profile.changeAvatar": "Đổi ảnh đại diện",
    "profile.avatarFormat": "JPEG hoặc PNG, tối đa 5MB",
    "profile.requiredField": "là bắt buộc",
    "profile.phoneInvalid": "Số điện thoại không hợp lệ (10-11 số)",
    "profile.selectGender": "Chọn giới tính",
    "profile.saving": "Đang lưu...",
    "profile.saveChanges": "Lưu thay đổi",
    "profile.receivePromoEmail": "Nhận email khuyến mãi từ CineHub",
    // About
    "about.hero.title": "CINEHUB",
    "about.hero.subtitle": "Trải nghiệm điện ảnh đỉnh cao",
    "about.title": "VỀ CHÚNG TÔI",
    "about.description1":
      "CineHub là hệ thống rạp chiếu phim hiện đại, được thành lập với sứ mệnh mang đến trải nghiệm điện ảnh tuyệt vời nhất cho khán giả Việt Nam.",
    "about.description2":
      "Với công nghệ chiếu phim tiên tiến, âm thanh vòm Dolby Atmos và ghế ngồi cao cấp, CineHub cam kết mang đến những giây phút giải trí đáng nhớ.",
    "about.description3":
      "Chúng tôi không ngừng đổi mới và phát triển để trở thành điểm đến yêu thích của mọi tín đồ điện ảnh.",
    "about.mission.title": "SỨ MỆNH CỦA CHÚNG TÔI",
    "about.mission1.title": "Chất lượng hàng đầu",
    "about.mission1.description":
      "Cam kết mang đến trải nghiệm xem phim chất lượng cao nhất với công nghệ hiện đại.",
    "about.mission2.title": "Ưu đãi hấp dẫn",
    "about.mission2.description":
      "Nhiều chương trình khuyến mãi và ưu đãi đặc biệt dành cho khách hàng thân thiết.",
    "about.mission3.title": "Phim đa dạng",
    "about.mission3.description":
      "Cập nhật liên tục các bộ phim bom tấn trong nước và quốc tế.",
    "about.theaters.title": "HỆ THỐNG RẠP",
    "about.theaters.description":
      "Khám phá hệ thống rạp CineHub trải dài khắp Việt Nam với cơ sở vật chất hiện đại.",
    "about.theaters.bookTicket": "Đặt vé",
    "about.theaters.loading": "Đang tải danh sách rạp...",
    // Movie Detail
    "movie.loading": "Đang tải...",
    "movie.notFound": "Không tìm thấy phim.",
    "movie.cannotLoad": "Không thể tải thông tin phim.",
    "movie.info": "Thông tin phim",
    "movie.comments": "Bình luận",
    "movie.minutes": "phút",
    "movie.watchTrailer": "Xem Trailer",
    "movie.details": "Thông tin",
    "movie.director": "Đạo diễn",
    "movie.cast": "Diễn viên",
    "movie.overview": "Nội dung phim",
    "movie.yourRating": "Bạn",
    "movie.ratings": "lượt đánh giá",
    "movie.addToFavorite": "Thêm vào yêu thích",
    "movie.removeFromFavorite": "Xóa khỏi yêu thích",
    "movie.loginRequired": "Chưa đăng nhập",
    "movie.loginToFavorite": "Vui lòng đăng nhập để thêm phim yêu thích!",
    "movie.login": "Đăng nhập",
    "movie.cancel": "Hủy",
    "movie.removedFromFavorite": "Đã xóa khỏi yêu thích",
    "movie.removedFromFavoriteDesc":
      "Phim đã được xóa khỏi danh sách yêu thích!",
    "movie.addedToFavorite": "Đã thêm vào yêu thích",
    "movie.addedToFavoriteDesc": "Phim đã được thêm vào danh sách yêu thích!",
    "movie.error": "Lỗi",
    "movie.cannotUpdateFavorite": "Không thể cập nhật phim yêu thích!",
    "movie.loginToRate": "Yêu cầu đăng nhập",
    "movie.loginToRateDesc": "Bạn cần đăng nhập để đánh giá phim",
    "movie.notBooked": "Chưa đặt vé phim này",
    "movie.notBookedDesc": "Bạn cần đặt vé xem phim này để có thể đánh giá",
    "movie.bookNow": "Đặt vé ngay",
    "movie.ratingSuccess": "Đánh giá thành công!",
    "movie.ratingSuccessDesc": "Bạn đã đánh giá {rating} sao cho phim này",
    "movie.ratingError": "Không thể gửi đánh giá. Vui lòng thử lại sau.",
    // Movie Comments
    "comment.loginRequired": "Cần đăng nhập",
    "comment.loginRequiredDesc": "Bạn cần đăng nhập để bình luận!",
    "comment.bookingRequired": "Cần đặt vé",
    "comment.bookingRequiredDesc":
      "Bạn cần đặt vé xem phim này để có thể bình luận!",
    "comment.tooShort": "Bình luận quá ngắn",
    "comment.tooShortDesc": "Vui lòng nhập ít nhất 3 ký tự!",
    "comment.error": "Lỗi",
    "comment.errorDesc": "Không thể gửi bình luận. Vui lòng thử lại sau.",
    "comment.noComments": "Chưa có bình luận nào.",
    "comment.loginPlaceholder": "Vui lòng đăng nhập để bình luận",
    "comment.bookingPlaceholder":
      "Vui lòng đặt vé xem phim này để có thể bình luận",
    "comment.placeholder": "Bạn nghĩ gì về bộ phim này?",
    "comment.sending": "Đang gửi...",
    "comment.send": "Gửi",
    // Theater Detail
    "theater.notFound": "Không tìm thấy rạp",
    "theater.introduction": "Giới thiệu",
    "theater.nowPlaying": "PHIM ĐANG CHIẾU",
    "theater.noShowtimes": "Hiện tại rạp chưa có suất chiếu nào",
    "theater.viewMoreShowtimes": "Xem thêm lịch chiếu",
    // FnB Page
    "fnb.title": "ĐẶT BẮP NƯỚC",
    "fnb.subtitle": "Thưởng thức bắp rang bơ và nước uống thơm ngon tại rạp",
    "fnb.selectTheater": "Chọn rạp để nhận hàng",
    "fnb.selectTheaterPlaceholder": "Chọn rạp nơi bạn muốn nhận",
    "fnb.menuTitle": "Thực đơn đặc biệt",
    "fnb.menuSubtitle":
      "Tất cả rạp đều có cùng thực đơn với chất lượng tuyệt vời",
    "fnb.noItems": "Hiện chưa có sản phẩm nào",
    "fnb.add": "Thêm",
    "fnb.creatingOrder": "Đang tạo đơn hàng...",
    "fnb.pleaseWait": "Vui lòng đợi trong giây lát",
    "fnb.loginRequired": "Yêu cầu đăng nhập",
    "fnb.loginRequiredDesc": "Bạn cần đăng nhập để đặt bắp nước",
    "fnb.login": "Đăng nhập",
    "fnb.cancel": "Hủy",
    "fnb.noTheaterSelected": "Chưa chọn rạp",
    "fnb.noTheaterSelectedDesc": "Vui lòng chọn rạp để tiếp tục đặt hàng!",
    "fnb.emptyCart": "Giỏ hàng trống",
    "fnb.emptyCartDesc": "Vui lòng chọn ít nhất một món để tiếp tục!",
    "fnb.cartError": "Lỗi giỏ hàng",
    "fnb.cartErrorDesc":
      "Tổng tiền phải lớn hơn 0. Vui lòng kiểm tra lại giỏ hàng!",
    "fnb.error": "Lỗi",
    "fnb.tryAgain": "Vui lòng thử lại!",
    "fnb.noTheater": "Chưa chọn rạp",
    // FnB Summary Bar
    "fnb.snacks": "Bắp nước",
    "fnb.itemCount": "Số lượng món",
    "fnb.items": "món",
    "fnb.subtotal": "Tạm tính",
    "fnb.continue": "TIẾP TỤC",
    "fnb.processing": "ĐANG XỬ LÝ...",
    // FnB Checkout Page
    "fnb.checkoutTitle": "ĐẶT BẮP NƯỚC",
    "fnb.checkoutSubtitle": "Hoàn tất đơn hàng và thanh toán",
    "fnb.step1": "CHỌN BẮP NƯỚC",
    "fnb.step2": "THANH TOÁN",
    "fnb.step3": "THÔNG TIN BẮP NƯỚC",
    "fnb.checkoutHighlight": "BẮP NƯỚC",
    "fnb.selectedItems": "Sản phẩm đã chọn",
    "fnb.theater": "Rạp",
    "fnb.address": "Địa chỉ",
    "fnb.payment": "Thanh toán",
    "fnb.customerInfo": "Thông tin khách hàng:",
    "fnb.payViaZaloPay": "Thanh toán qua ZaloPay",
    "fnb.redirectToZaloPay":
      "Bạn sẽ được chuyển đến ZaloPay để hoàn tất thanh toán",
    "fnb.backToSelect": "← Quay lại chọn món",
    "fnb.payNow": "Thanh toán ngay",
    "fnb.processingPayment": "Đang xử lý...",
    "fnb.noOrderInfo": "Không có thông tin đơn hàng",
    "fnb.backToOrder": "Quay lại đặt bắp nước",
    "fnb.timeExpired": "Hết thời gian",
    "fnb.orderExpired": "Đơn hàng đã hết hạn. Vui lòng đặt lại.",
    "fnb.orderNotFound": "Không tìm thấy thông tin đơn hàng",
    "fnb.paymentLinkError": "Không thể tạo link thanh toán",
    // FnB Order Summary
    "fnb.yourOrder": "Đơn hàng của bạn",
    "fnb.orderCode": "Mã đơn hàng:",
    "fnb.timeRemaining": "Thời gian còn lại",
    "fnb.total": "Tổng cộng:",
    // Showtime Page
    "showtime.title": "LỊCH CHIẾU PHIM",
    "showtime.subtitle": "Tìm suất chiếu phù hợp với bạn",
    "showtime.date": "Ngày",
    "showtime.movie": "Phim",
    "showtime.theater": "Rạp",
    "showtime.selectDate": "Chọn ngày",
    "showtime.selectMovie": "Tất cả phim",
    "showtime.selectTheater": "Tất cả rạp",
    "showtime.noShowtimes": "Chưa có suất chiếu",
    "showtime.tryOther": "Vui lòng thử chọn ngày hoặc rạp khác",
    // Payment Result
    "payment.processing": "Đang xử lý thanh toán...",
    "payment.pleaseWait": "Vui lòng đợi trong giây lát",
    "payment.success": "Thanh toán thành công!",
    "payment.thankYou": "Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi",
    "payment.emailSent":
      "Vé đã được gửi qua email, vui lòng kiểm tra và check-in tại quầy",
    "payment.redirectBookings": "Đang chuyển hướng đến trang lịch sử đặt vé...",
    "payment.redirectFnb": "Đang chuyển hướng đến lịch sử bắp nước...",
    "payment.failed": "Thanh toán thất bại",
    "payment.backHome": "Về trang chủ",
    "payment.noTransaction": "Không tìm thấy thông tin giao dịch",
    "payment.notCompleted": "Giao dịch chưa được thực hiện",
    "payment.checkError": "Không thể kiểm tra trạng thái thanh toán",
    // Booking Flow - MovieShowtime
    "booking.scheduleTitle": "Lịch Chiếu",
    "booking.scheduleHighlight": "Phim",
    "booking.today": "Hôm nay",
    "booking.theaterList": "DANH SÁCH RẠP",
    "booking.selectProvince": "Chọn tỉnh/thành phố",
    "booking.noShowtimesArea": "Chưa có suất chiếu nào tại khu vực này.",
    "booking.noShowtimesToday": "Hết suất chiếu hôm nay",
    "booking.noScheduleYet": "Hiện chưa có lịch chiếu cho phim này.",
    "booking.selectTicketType": "Chọn loại",
    "booking.ticketHighlight": "Vé",
    "booking.seatMap": "Sơ đồ",
    "booking.seatHighlight": "Ghế",
    "booking.seatExpired": "Hết thời gian giữ ghế",
    "booking.seatExpiredText": "Vui lòng chọn lại ghế!",
    "booking.noShowtimeSelected": "Bạn chưa chọn lịch chiếu!",
    "booking.noSeatSelected": "Bạn chưa chọn ghế!",
    "booking.noTicketSelected": "Bạn chưa chọn loại vé!",
    "booking.ticketSeatMismatch": "Số lượng vé và ghế không khớp!",
    "booking.creatingTicket": "Đang khởi tạo vé...",
    "booking.error": "Lỗi",
    "booking.cannotCreateOrder": "Không thể tạo đơn hàng. Vui lòng thử lại.",
    // Checkout - SelectComboStep
    "checkout.cancelBooking": "Hủy đặt vé?",
    "checkout.cancelBookingText":
      "Ghế bạn đang giữ sẽ được mở khóa. Bạn có chắc muốn quay lại?",
    "checkout.confirm": "Đồng ý",
    "checkout.stay": "Ở lại",
    "checkout.back": "Quay lại",
    "checkout.next": "Tiếp theo",
    "checkout.continue": "Tiếp tục",
    // Checkout - CustomerInfoStep
    "checkout.fullName": "Họ và tên",
    "checkout.email": "Email",
    "checkout.phone": "Số điện thoại",
    "checkout.fullNameRequired": "Họ và tên là bắt buộc",
    "checkout.emailRequired": "Email là bắt buộc",
    "checkout.emailInvalid": "Email không hợp lệ",
    "checkout.phoneRequired": "Số điện thoại là bắt buộc",
    "checkout.phoneInvalid": "Số điện thoại không hợp lệ",
    "checkout.ageConfirm": "Đảm bảo mua vé đúng số tuổi quy định.",
    "checkout.termsAgree": "Đồng ý với điều khoản của CineHub.",
    "checkout.ageRequired": "Bạn cần xác nhận đúng độ tuổi",
    "checkout.termsRequired": "Bạn cần đồng ý điều khoản",
    "checkout.invalidInfo": "Thông tin chưa hợp lệ",
    // Checkout - PaymentStep
    "checkout.rankDiscount": "Giảm giá theo hạng",
    "checkout.rank": "Hạng",
    "checkout.rankDiscountDesc": "Giảm giá dành riêng cho thành viên hạng",
    "checkout.discount": "Giảm",
    "checkout.promoCode": "Mã giảm giá",
    "checkout.loadingPromo": "Đang tải mã giảm giá...",
    "checkout.noPromo": "Không có mã giảm giá nào",
    "checkout.canUse": "Có thể sử dụng",
    "checkout.cannotUse": "Không thể sử dụng",
    "checkout.loginToUsePromo": "Đăng nhập để sử dụng mã giảm giá",
    "checkout.paymentError": "Lỗi thanh toán",
    "checkout.noBookingInfo":
      "Không tìm thấy thông tin booking. Vui lòng thử lại!",
    "checkout.cannotCreatePayment":
      "Không thể tạo liên kết thanh toán. Vui lòng thử lại!",
    "checkout.creatingPayment": "Đang tạo liên kết thanh toán...",
    "checkout.confirmPay": "Xác nhận & Thanh toán",
    "checkout.discountPercent": "Giảm",
    "checkout.discountAmount": "Giảm",
    // Checkout - CheckoutPage
    "checkout.title": "THANH",
    "checkout.titleHighlight": "TOÁN",
    "checkout.step1": "THÔNG TIN KHÁCH HÀNG",
    "checkout.step2": "CHỌN BẮP NƯỚC",
    "checkout.step3": "MÃ GIẢM GIÁ",
    "checkout.step4": "THANH TOÁN",
    "checkout.seatExpired": "Hết thời gian giữ ghế",
    "checkout.seatExpiredText": "Vui lòng thực hiện đặt vé lại!",
    "checkout.rebookTicket": "Đặt vé lại",
    // Checkout - BookingSummary
    "checkout.orderSummary": "Tóm tắt đơn hàng",
    "checkout.holdTime": "Thời gian giữ vé",
    "checkout.movie": "Phim",
    "checkout.theater": "Rạp",
    "checkout.room": "Phòng",
    "checkout.time": "Thời gian",
    "checkout.seats": "Ghế",
    "checkout.memberRank": "Hạng thành viên",
    "checkout.combo": "Combo",
    "checkout.noCombo": "Không có combo",
    "checkout.subtotal": "Tạm tính",
    "checkout.promoDiscount": "Mã giảm giá",
    "checkout.rankDiscountLabel": "Giảm giá hạng",
    "checkout.total": "Tổng",
    // Checkout - ConfirmStep
    "checkout.confirmOrder": "Xác nhận đơn hàng",
    "checkout.pay": "Thanh toán",
    // SelectCombo
    "checkout.loadingCombo": "Đang tải combo...",
    // SelectTicket
    "ticket.adult": "Người lớn",
    "ticket.child": "Trẻ em",
    "ticket.student": "HSSV-U22",
    "ticket.couple": "Đôi",
    "ticket.single": "Đơn",
    "ticket.notExist": "Loại vé không tồn tại.",
    "ticket.studentNote": "Lưu ý vé HSSV-U22",
    "ticket.studentNoteHtml":
      '<div class="text-left"><p class="mb-3">Khi sử dụng vé HSSV-U22, bạn cần mang theo:</p><ul class="list-disc list-inside space-y-1 text-sm"><li><strong>Thẻ sinh viên</strong> hoặc <strong>Thẻ học sinh</strong> còn hạn</li><li><strong>Căn cước công dân</strong> để xác minh tuổi (dưới 22 tuổi)</li></ul><p class="mt-3 text-sm text-gray-600">Nhân viên rạp sẽ kiểm tra giấy tờ trước khi vào phòng chiếu.</p></div>',
    "ticket.understood": "Đã hiểu",
    // SelectSeat
    "seat.loading": "Đang tải sơ đồ ghế...",
    "seat.noData": "Không có dữ liệu ghế.",
    "seat.holdExpired": "Hết thời gian giữ ghế",
    "seat.holdExpiredText":
      "Ghế bạn đang giữ đã bị giải phóng. Vui lòng chọn lại ghế!",
    "seat.entrance": "Lối vào",
    "seat.screen": "MÀN HÌNH",
    "seat.normal": "Ghế thường",
    "seat.vip": "Ghế VIP",
    "seat.coupleSeat": "Ghế đôi",
    "seat.selected": "Ghế chọn",
    "seat.holding": "Đang giữ chỗ",
    "seat.booked": "Đã đặt",
    "seat.noCoupleTicket": "Chưa chọn vé đôi",
    "seat.noCoupleTicketText": "Vui lòng chọn vé đôi trước!",
    "seat.coupleEnough": "Đã đủ ghế đôi",
    "seat.coupleEnoughText": "Bạn chỉ mua {count} vé đôi!",
    "seat.noSingleTicket": "Chưa chọn vé đơn",
    "seat.noSingleTicketText": "Vui lòng chọn vé đơn trước!",
    "seat.singleEnough": "Đã đủ ghế đơn",
    "seat.singleEnoughText": "Bạn chỉ mua {count} vé đơn!",
    "seat.alreadyLocked": "Ghế đã được giữ",
    "seat.alreadyLockedText": "Ghế này vừa được người khác chọn.",
    "seat.error": "Lỗi",
    "seat.errorText": "Không thể chọn ghế. Vui lòng thử lại!",
    // BookingSummaryBar
    "summaryBar.holdTime": "Thời gian giữ vé",
    "summaryBar.subtotal": "Tạm tính",
    "summaryBar.bookTicket": "ĐẶT VÉ",
    "summaryBar.noSeat": "Chưa chọn ghế!",
    "summaryBar.noSeatText":
      "Vui lòng chọn ghế trước khi tiến hành thanh toán.",
    // Auth Page
    "auth.login": "Đăng Nhập",
    "auth.loginWelcome": "Chào mừng bạn quay trở lại CineHub!",
    "auth.accountLabel": "Tài khoản / Email / Số điện thoại",
    "auth.accountPlaceholder": "nguyenvana",
    "auth.passwordLabel": "Mật khẩu",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "Ghi nhớ đăng nhập",
    "auth.forgotPassword": "Quên mật khẩu?",
    "auth.loginButton": "ĐĂNG NHẬP",
    "auth.register": "Đăng Ký",
    "auth.createAccount": "Tạo Tài Khoản",
    "auth.registerWelcome": "Cùng chiêm ngưỡng những bộ phim bom tấn",
    "auth.usernameLabel": "Tên đăng nhập",
    "auth.usernamePlaceholder": "nguyenvana",
    "auth.emailLabel": "Email",
    "auth.emailPlaceholder": "example@gmail.com",
    "auth.phoneLabel": "Số điện thoại",
    "auth.phonePlaceholder": "0912345678",
    "auth.nationalIdLabel": "CMND/CCCD",
    "auth.nationalIdPlaceholder": "0791...",
    "auth.confirmPasswordLabel": "Xác nhận mật khẩu",
    "auth.confirmPasswordPlaceholder": "Nhập lại mật khẩu",
    "auth.minChars": "Tối thiểu 6 ký tự",
    "auth.registerButton": "ĐĂNG KÝ",
    "auth.welcomeBack": "Chào mừng trở lại!",
    "auth.welcomeBackDesc":
      "Để duy trì kết nối với CineHub, vui lòng đăng nhập bằng thông tin cá nhân của bạn",
    "auth.helloNew": "Xin chào, Bạn mới!",
    "auth.helloNewDesc":
      "Nhập thông tin cá nhân của bạn và bắt đầu hành trình tuyệt vời cùng",
    // Auth Validation
    "auth.error.accountRequired": "Vui lòng nhập tài khoản",
    "auth.error.passwordRequired": "Vui lòng nhập mật khẩu",
    "auth.error.emailInvalid": "Email không hợp lệ",
    "auth.error.usernameMin": "Tên đăng nhập tối thiểu 3 ký tự",
    "auth.error.phoneInvalid": "SĐT không hợp lệ",
    "auth.error.nationalIdInvalid": "CMND/CCCD không hợp lệ",
    "auth.error.passwordMin": "Mật khẩu tối thiểu 6 ký tự",
    "auth.error.passwordMismatch": "Mật khẩu không khớp",
  },
  en: {
    // Header
    "header.about": "About",
    "header.search": "Search movies...",
    "header.login": "Login",
    "header.profile": "Profile",
    "header.dashboard": "Dashboard",
    "header.logout": "Logout",
    // Home
    "home.hero.title": "CINEHUB",
    "home.hero.subtitle": "Premium Cinema Experience",
    "home.nowPlaying": "NOW PLAYING",
    "home.upcoming": "UPCOMING",
    "home.promotions": "PROMOTIONS",
    "home.contact": "CONTACT",
    "home.learnMore": "More",
    "home.bookTicket": "Book",
    "home.bookNow": "Book Now",
    "home.seeMore": "See More",
    "home.noMoviesPlaying": "No movies currently playing",
    "home.noMoviesUpcoming": "No upcoming movies",
    // Quick Booking Bar
    "home.booking.title": "QUICK BOOKING",
    "home.booking.movie": "Movie",
    "home.booking.theater": "Theater",
    "home.booking.date": "Date",
    "home.booking.showtime": "Showtime",
    "home.booking.bookNow": "BOOK NOW!",
    // Footer
    "footer.theaterSystem": "Theater System",
    "footer.contact": "Contact",
    "footer.policy": "Policy",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.description":
      "CineHub - Modern cinema system, delivering premium movie experience with the most advanced technology.",
    "footer.rights": "All rights reserved.",
    // Search
    "search.resultsFor": "Search results for",
    "search.found": "Found",
    "search.movies": "movies",
    "search.and": "and",
    "search.theatersCount": "theaters",
    "search.moviesSection": "MOVIES",
    "search.theaters": "THEATERS",
    "search.book": "Book",
    "search.enterKeyword": "Please enter a search keyword",
    "search.noResults": "No results found",
    // Contact
    "contact.university": "UIT - University of Information Technology",
    "contact.address": "Address",
    "contact.description":
      "We are always ready to listen and support you. Please contact us through the channels below.",
    "contact.title": "Send us a message",
    "contact.name": "Full name",
    "contact.namePlaceholder": "Enter your full name",
    "contact.nameRequired": "Please enter your name",
    "contact.nameMinLength": "Name must be at least 2 characters",
    "contact.email": "Email",
    "contact.emailRequired": "Please enter your email",
    "contact.emailInvalid": "Invalid email address",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Enter your message...",
    "contact.messageRequired": "Please enter your message",
    "contact.messageMinLength": "Message must be at least 10 characters",
    "contact.messageMaxLength": "Message cannot exceed 1000 characters",
    "contact.send": "Send message",
    "contact.sending": "Sending...",
    "contact.success": "Success!",
    "contact.successMessage":
      "Your message has been sent successfully. We will respond as soon as possible.",
    "contact.error": "Error!",
    "contact.errorMessage":
      "An error occurred while sending your message. Please try again later.",
    // Common
    "common.loading": "Loading...",
    "common.confirm": "Confirm",
    // Profile
    "profile.loading": "Loading...",
    "profile.cannotLoad": "Cannot load profile information",
    "profile.info": "Info",
    "profile.bookings": "Bookings",
    "profile.fnb": "F&B",
    "profile.favorites": "Favorites",
    "profile.loyalty": "Loyalty",
    "profile.notUpdated": "Not updated",
    "profile.edit": "Edit",
    "profile.ticketsBooked": "Tickets booked",
    "profile.favoriteMovies": "Favorite movies",
    "profile.loyaltyPoints": "Loyalty points",
    "profile.memberRank": "Member rank: ",
    "profile.rankProgress": "Rank progress",
    "profile.fullName": "Full name",
    "profile.email": "Email",
    "profile.phone": "Phone number",
    "profile.gender": "Gender",
    "profile.male": "Male",
    "profile.female": "Female",
    "profile.other": "Other",
    "profile.address": "Address",
    "profile.dateOfBirth": "Date of Birth",
    "profile.nationalId": "National ID",
    "profile.status": "Status",
    "profile.createdDate": "Created Date",
    "profile.active": "Active",
    "profile.blocked": "Blocked",
    "profile.noBookingHistory": "No booking history",
    "profile.bookingHistoryDesc": "Your booking history will appear here",
    "profile.bookingCode": "Booking code",
    "profile.theater": "Theater",
    "profile.room": "Room",
    "profile.showtime": "Showtime",
    "profile.seats": "Seats",
    "profile.seeMore": "See more",
    "profile.noFavoriteMovies": "No favorite movies",
    "profile.favoriteMoviesDesc": "Add favorite movies to watch later",
    "profile.noFnbHistory": "No F&B order history",
    "profile.fnbHistoryDesc": "Your F&B order history will appear here",
    "profile.orderNow": "Order now",
    "profile.fnbOrder": "F&B Order",
    "profile.orderCode": "Order code",
    "profile.confirmed": "Confirmed",
    "profile.pending": "Pending",
    "profile.cancelled": "Cancelled",
    "profile.orderedItems": "Ordered items",
    "profile.orderTime": "Order time",
    "profile.total": "Total",
    "profile.membershipRank": "Membership rank",
    "profile.currentPoints": "Current points",
    "profile.pointsRemaining": "Need",
    "profile.pointsToNext": "points to next rank",
    "profile.loyaltyHistory": "Loyalty history",
    "profile.noLoyaltyHistory": "No loyalty history",
    "profile.loyaltyHistoryDesc": "Book movie tickets to earn loyalty points",
    "profile.bookNow": "Book now",
    "profile.exploreMovies": "Explore movies",
    "profile.earned": "Earned",
    "profile.redeemed": "Redeemed",
    "profile.bonus": "Bonus",
    "profile.expired": "Expired",
    "profile.points": "points",
    "profile.changeAvatar": "Change avatar",
    "profile.avatarFormat": "JPEG or PNG, max 5MB",
    "profile.requiredField": "is required",
    "profile.phoneInvalid": "Invalid phone number (10-11 digits)",
    "profile.selectGender": "Select gender",
    "profile.saving": "Saving...",
    "profile.saveChanges": "Save changes",
    "profile.receivePromoEmail": "Receive promotional emails from CineHub",
    // About
    "about.hero.title": "CINEHUB",
    "about.hero.subtitle": "Premium Cinema Experience",
    "about.title": "ABOUT US",
    "about.description1":
      "CineHub is a modern cinema system, established with the mission of bringing the best cinematic experience to Vietnamese audiences.",
    "about.description2":
      "With advanced projection technology, Dolby Atmos surround sound and premium seating, CineHub is committed to delivering memorable entertainment moments.",
    "about.description3":
      "We continuously innovate and develop to become the favorite destination for all movie lovers.",
    "about.mission.title": "OUR MISSION",
    "about.mission1.title": "Top Quality",
    "about.mission1.description":
      "Committed to delivering the highest quality movie experience with modern technology.",
    "about.mission2.title": "Attractive Offers",
    "about.mission2.description":
      "Many promotions and special offers for loyal customers.",
    "about.mission3.title": "Diverse Movies",
    "about.mission3.description":
      "Continuously updated with domestic and international blockbusters.",
    "about.theaters.title": "THEATER SYSTEM",
    "about.theaters.description":
      "Discover the CineHub theater system spanning across Vietnam with modern facilities.",
    "about.theaters.bookTicket": "Book Ticket",
    "about.theaters.loading": "Loading theaters...",
    // Movie Detail
    "movie.loading": "Loading...",
    "movie.notFound": "Movie not found.",
    "movie.cannotLoad": "Cannot load movie information.",
    "movie.info": "Movie Info",
    "movie.comments": "Comments",
    "movie.minutes": "min",
    "movie.watchTrailer": "Watch Trailer",
    "movie.details": "Details",
    "movie.director": "Director",
    "movie.cast": "Cast",
    "movie.overview": "Overview",
    "movie.yourRating": "You",
    "movie.ratings": "ratings",
    "movie.addToFavorite": "Add to favorites",
    "movie.removeFromFavorite": "Remove from favorites",
    "movie.loginRequired": "Login Required",
    "movie.loginToFavorite": "Please login to add favorite movies!",
    "movie.login": "Login",
    "movie.cancel": "Cancel",
    "movie.removedFromFavorite": "Removed from favorites",
    "movie.removedFromFavoriteDesc":
      "Movie has been removed from your favorites!",
    "movie.addedToFavorite": "Added to favorites",
    "movie.addedToFavoriteDesc": "Movie has been added to your favorites!",
    "movie.error": "Error",
    "movie.cannotUpdateFavorite": "Cannot update favorite movies!",
    "movie.loginToRate": "Login Required",
    "movie.loginToRateDesc": "You need to login to rate this movie",
    "movie.notBooked": "Haven't booked this movie",
    "movie.notBookedDesc":
      "You need to book a ticket for this movie to rate it",
    "movie.bookNow": "Book Now",
    "movie.ratingSuccess": "Rating Successful!",
    "movie.ratingSuccessDesc": "You rated this movie {rating} stars",
    "movie.ratingError": "Cannot submit rating. Please try again later.",
    // Movie Comments
    "comment.loginRequired": "Login Required",
    "comment.loginRequiredDesc": "You need to login to comment!",
    "comment.bookingRequired": "Booking Required",
    "comment.bookingRequiredDesc":
      "You need to book a ticket for this movie to comment!",
    "comment.tooShort": "Comment too short",
    "comment.tooShortDesc": "Please enter at least 3 characters!",
    "comment.error": "Error",
    "comment.errorDesc": "Cannot submit comment. Please try again later.",
    "comment.noComments": "No comments yet.",
    "comment.loginPlaceholder": "Please login to comment",
    "comment.bookingPlaceholder":
      "Please book a ticket for this movie to comment",
    "comment.placeholder": "What do you think about this movie?",
    "comment.sending": "Sending...",
    "comment.send": "Send",
    // Theater Detail
    "theater.notFound": "Theater not found",
    "theater.introduction": "Introduction",
    "theater.nowPlaying": "NOW PLAYING",
    "theater.noShowtimes": "No showtimes available at this theater",
    "theater.viewMoreShowtimes": "View more showtimes",
    // FnB Page
    "fnb.title": "ORDER SNACKS",
    "fnb.subtitle": "Enjoy delicious popcorn and drinks at the theater",
    "fnb.selectTheater": "Select theater for pickup",
    "fnb.selectTheaterPlaceholder": "Select a theater near you",
    "fnb.menuTitle": "Special Menu",
    "fnb.menuSubtitle":
      "All theaters have the same menu with excellent quality",
    "fnb.noItems": "No products available",
    "fnb.add": "Add",
    "fnb.creatingOrder": "Creating order...",
    "fnb.pleaseWait": "Please wait a moment",
    "fnb.loginRequired": "Login Required",
    "fnb.loginRequiredDesc": "You need to login to order snacks",
    "fnb.login": "Login",
    "fnb.cancel": "Cancel",
    "fnb.noTheaterSelected": "No theater selected",
    "fnb.noTheaterSelectedDesc":
      "Please select a theater to continue ordering!",
    "fnb.emptyCart": "Empty cart",
    "fnb.emptyCartDesc": "Please select at least one item to continue!",
    "fnb.cartError": "Cart error",
    "fnb.cartErrorDesc":
      "Total amount must be greater than 0. Please check your cart!",
    "fnb.error": "Error",
    "fnb.tryAgain": "Please try again!",
    "fnb.noTheater": "No theater selected",
    // FnB Summary Bar
    "fnb.snacks": "Snacks",
    "fnb.itemCount": "Item count",
    "fnb.items": "items",
    "fnb.subtotal": "Subtotal",
    "fnb.continue": "CONTINUE",
    "fnb.processing": "PROCESSING...",
    // FnB Checkout Page
    "fnb.checkoutTitle": "ORDER SNACKS",
    "fnb.checkoutSubtitle": "Complete your order and payment",
    "fnb.step1": "SELECT SNACKS",
    "fnb.step2": "PAYMENT",
    "fnb.step3": "SNACK INFO",
    "fnb.checkoutHighlight": "SNACKS",
    "fnb.selectedItems": "Selected Items",
    "fnb.theater": "Theater",
    "fnb.address": "Address",
    "fnb.payment": "Payment",
    "fnb.customerInfo": "Customer information:",
    "fnb.payViaZaloPay": "Pay via ZaloPay",
    "fnb.redirectToZaloPay":
      "You will be redirected to ZaloPay to complete payment",
    "fnb.backToSelect": "← Back to select items",
    "fnb.payNow": "Pay Now",
    "fnb.processingPayment": "Processing...",
    "fnb.noOrderInfo": "No order information",
    "fnb.backToOrder": "Back to order snacks",
    "fnb.timeExpired": "Time expired",
    "fnb.orderExpired": "Order has expired. Please order again.",
    "fnb.orderNotFound": "Order information not found",
    "fnb.paymentLinkError": "Cannot create payment link",
    // FnB Order Summary
    "fnb.yourOrder": "Your Order",
    "fnb.orderCode": "Order code:",
    "fnb.timeRemaining": "Time remaining",
    "fnb.total": "Total:",
    // Showtime Page
    "showtime.title": "SHOWTIMES",
    "showtime.subtitle": "Find the perfect showtime for you",
    "showtime.date": "Date",
    "showtime.movie": "Movie",
    "showtime.theater": "Theater",
    "showtime.selectDate": "Select date",
    "showtime.selectMovie": "All Movies",
    "showtime.selectTheater": "All Theaters",
    "showtime.noShowtimes": "No showtimes available",
    "showtime.tryOther": "Please try selecting a different date or theater",
    // Payment Result
    "payment.processing": "Processing payment...",
    "payment.pleaseWait": "Please wait a moment",
    "payment.success": "Payment successful!",
    "payment.thankYou": "Thank you for using our service",
    "payment.emailSent":
      "Ticket has been sent to your email, please check and check-in at the counter",
    "payment.redirectBookings": "Redirecting to booking history...",
    "payment.redirectFnb": "Redirecting to F&B order history...",
    "payment.failed": "Payment failed",
    "payment.backHome": "Back to Home",
    "payment.noTransaction": "Transaction information not found",
    "payment.notCompleted": "Transaction was not completed",
    "payment.checkError": "Unable to check payment status",
    // Booking Flow - MovieShowtime
    "booking.scheduleTitle": "Movie",
    "booking.scheduleHighlight": "Schedule",
    "booking.today": "Today",
    "booking.theaterList": "THEATER LIST",
    "booking.selectProvince": "Select province/city",
    "booking.noShowtimesArea": "No showtimes available in this area.",
    "booking.noShowtimesToday": "No more showtimes today",
    "booking.noScheduleYet": "No schedule available for this movie yet.",
    "booking.selectTicketType": "Select Ticket",
    "booking.ticketHighlight": "Type",
    "booking.seatMap": "Seat",
    "booking.seatHighlight": "Map",
    "booking.seatExpired": "Seat hold time expired",
    "booking.seatExpiredText": "Please select seats again!",
    "booking.noShowtimeSelected": "Please select a showtime!",
    "booking.noSeatSelected": "Please select seats!",
    "booking.noTicketSelected": "Please select ticket type!",
    "booking.ticketSeatMismatch": "Number of tickets and seats don't match!",
    "booking.creatingTicket": "Creating ticket...",
    "booking.error": "Error",
    "booking.cannotCreateOrder": "Cannot create order. Please try again.",
    // Checkout - SelectComboStep
    "checkout.cancelBooking": "Cancel booking?",
    "checkout.cancelBookingText":
      "Your held seats will be released. Are you sure you want to go back?",
    "checkout.confirm": "Confirm",
    "checkout.stay": "Stay",
    "checkout.back": "Back",
    "checkout.next": "Next",
    "checkout.continue": "Continue",
    // Checkout - CustomerInfoStep
    "checkout.fullName": "Full name",
    "checkout.email": "Email",
    "checkout.phone": "Phone number",
    "checkout.fullNameRequired": "Full name is required",
    "checkout.emailRequired": "Email is required",
    "checkout.emailInvalid": "Invalid email",
    "checkout.phoneRequired": "Phone number is required",
    "checkout.phoneInvalid": "Invalid phone number",
    "checkout.ageConfirm":
      "I confirm that I am purchasing tickets for the appropriate age group.",
    "checkout.termsAgree": "I agree to CineHub's terms and conditions.",
    "checkout.ageRequired": "You must confirm the age requirement",
    "checkout.termsRequired": "You must agree to the terms",
    "checkout.invalidInfo": "Invalid information",
    // Checkout - PaymentStep
    "checkout.rankDiscount": "Rank Discount",
    "checkout.rank": "Rank",
    "checkout.rankDiscountDesc": "Exclusive discount for",
    "checkout.discount": "Discount",
    "checkout.promoCode": "Promo Code",
    "checkout.loadingPromo": "Loading promo codes...",
    "checkout.noPromo": "No promo codes available",
    "checkout.canUse": "Available",
    "checkout.cannotUse": "Not available",
    "checkout.loginToUsePromo": "Login to use promo codes",
    "checkout.paymentError": "Payment error",
    "checkout.noBookingInfo":
      "Booking information not found. Please try again!",
    "checkout.cannotCreatePayment":
      "Cannot create payment link. Please try again!",
    "checkout.creatingPayment": "Creating payment link...",
    "checkout.confirmPay": "Confirm & Pay",
    "checkout.discountPercent": "Discount",
    "checkout.discountAmount": "Discount",
    // Checkout - CheckoutPage
    "checkout.title": "CHECK",
    "checkout.titleHighlight": "OUT",
    "checkout.step1": "CUSTOMER INFO",
    "checkout.step2": "SELECT SNACKS",
    "checkout.step3": "PROMO CODE",
    "checkout.step4": "PAYMENT",
    "checkout.seatExpired": "Seat hold time expired",
    "checkout.seatExpiredText": "Please book tickets again!",
    "checkout.rebookTicket": "Book Again",
    // Checkout - BookingSummary
    "checkout.orderSummary": "Order Summary",
    "checkout.holdTime": "Hold Time",
    "checkout.movie": "Movie",
    "checkout.theater": "Theater",
    "checkout.room": "Room",
    "checkout.time": "Time",
    "checkout.seats": "Seats",
    "checkout.memberRank": "Member Rank",
    "checkout.combo": "Combo",
    "checkout.noCombo": "No combo",
    "checkout.subtotal": "Subtotal",
    "checkout.promoDiscount": "Promo Code",
    "checkout.rankDiscountLabel": "Rank Discount",
    "checkout.total": "Total",
    // Checkout - ConfirmStep
    "checkout.confirmOrder": "Confirm Order",
    "checkout.pay": "Pay",
    // SelectCombo
    "checkout.loadingCombo": "Loading combos...",
    // SelectTicket
    "ticket.adult": "Adult",
    "ticket.child": "Child",
    "ticket.student": "Student U22",
    "ticket.couple": "Couple",
    "ticket.single": "Single",
    "ticket.notExist": "Ticket type does not exist.",
    "ticket.studentNote": "Student U22 Ticket Notice",
    "ticket.studentNoteHtml":
      '<div class="text-left"><p class="mb-3">When using Student U22 tickets, please bring:</p><ul class="list-disc list-inside space-y-1 text-sm"><li><strong>Valid student ID card</strong></li><li><strong>National ID</strong> to verify age (under 22 years old)</li></ul><p class="mt-3 text-sm text-gray-600">Staff will check your documents before entering the theater.</p></div>',
    "ticket.understood": "Understood",
    // SelectSeat
    "seat.loading": "Loading seat map...",
    "seat.noData": "No seat data available.",
    "seat.holdExpired": "Seat hold time expired",
    "seat.holdExpiredText":
      "Your held seats have been released. Please select seats again!",
    "seat.entrance": "Entrance",
    "seat.screen": "SCREEN",
    "seat.normal": "Standard",
    "seat.vip": "VIP",
    "seat.coupleSeat": "Couple",
    "seat.selected": "Selected",
    "seat.holding": "Holding",
    "seat.booked": "Booked",
    "seat.noCoupleTicket": "No couple ticket selected",
    "seat.noCoupleTicketText": "Please select couple ticket first!",
    "seat.coupleEnough": "Couple seats full",
    "seat.coupleEnoughText": "You only bought {count} couple tickets!",
    "seat.noSingleTicket": "No single ticket selected",
    "seat.noSingleTicketText": "Please select single ticket first!",
    "seat.singleEnough": "Single seats full",
    "seat.singleEnoughText": "You only bought {count} single tickets!",
    "seat.alreadyLocked": "Seat already held",
    "seat.alreadyLockedText": "This seat was just selected by someone else.",
    "seat.error": "Error",
    "seat.errorText": "Cannot select seat. Please try again!",
    // BookingSummaryBar
    "summaryBar.holdTime": "Hold Time",
    "summaryBar.subtotal": "Subtotal",
    "summaryBar.bookTicket": "BOOK",
    "summaryBar.noSeat": "No seat selected!",
    "summaryBar.noSeatText":
      "Please select seats before proceeding to payment.",
    // Auth Page
    "auth.login": "Sign In",
    "auth.loginWelcome": "Welcome back to CineHub!",
    "auth.accountLabel": "Username / Email / Phone",
    "auth.accountPlaceholder": "johndoe",
    "auth.passwordLabel": "Password",
    "auth.passwordPlaceholder": "••••••••",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.loginButton": "SIGN IN",
    "auth.register": "Sign Up",
    "auth.createAccount": "Create Account",
    "auth.registerWelcome": "Discover amazing blockbuster movies",
    "auth.usernameLabel": "Username",
    "auth.usernamePlaceholder": "johndoe",
    "auth.emailLabel": "Email",
    "auth.emailPlaceholder": "example@gmail.com",
    "auth.phoneLabel": "Phone number",
    "auth.phonePlaceholder": "0912345678",
    "auth.nationalIdLabel": "National ID",
    "auth.nationalIdPlaceholder": "0791...",
    "auth.confirmPasswordLabel": "Confirm password",
    "auth.confirmPasswordPlaceholder": "Re-enter password",
    "auth.minChars": "Minimum 6 characters",
    "auth.registerButton": "SIGN UP",
    "auth.welcomeBack": "Welcome Back!",
    "auth.welcomeBackDesc":
      "To stay connected with CineHub, please sign in with your personal info",
    "auth.helloNew": "Hello, Friend!",
    "auth.helloNewDesc":
      "Enter your personal details and start your amazing journey with",
    // Auth Validation
    "auth.error.accountRequired": "Please enter your account",
    "auth.error.passwordRequired": "Please enter your password",
    "auth.error.emailInvalid": "Invalid email address",
    "auth.error.usernameMin": "Username must be at least 3 characters",
    "auth.error.phoneInvalid": "Invalid phone number",
    "auth.error.nationalIdInvalid": "Invalid National ID",
    "auth.error.passwordMin": "Password must be at least 6 characters",
    "auth.error.passwordMismatch": "Passwords do not match",
  },
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get from localStorage or default to Vietnamese
    const saved = localStorage.getItem("cinehub-language");
    return (saved as Language) || "vi";
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem("cinehub-language", lang);
    setLanguageState(lang);
  };

  const toggleLanguage = () => {
    const newLang = language === "vi" ? "en" : "vi";
    setLanguage(newLang);
  };

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)["vi"]] || key
    );
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, toggleLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
