export const GENRES_OPTIONS = [
  "Tất cả",
  "Phim Hành Động",
  "Phim Phiêu Lưu",
  "Phim Hoạt Hình",
  "Phim Hài",
  "Phim Tội Phạm",
  "Phim Tài Liệu",
  "Phim Chính Kịch",
  "Phim Gia Đình",
  "Phim Giả Tưởng",
  "Phim Lịch Sử",
  "Phim Kinh Dị",
  "Phim Nhạc",
  "Phim Bí Ẩn",
  "Phim Lãng Mạn",
  "Phim Khoa Học Viễn Tưởng",
  "Phim Truyền Hình",
  "Phim Gây Cấn",
  "Phim Chiến Tranh",
  "Phim Miền Tây",
] as const;
